name: Synthesis

on: [pull_request, push]

jobs:
  synthesis:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - ./bluetooth
          - ./encoder_test1
          - ./feedback
          - ./maze_solver
          - ./remote_control

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Download yosys
        run: wget https://github.com/YosysHQ/oss-cad-suite-build/releases/download/2022-05-02/oss-cad-suite-linux-x64-20220502.tgz

      - name: Extract archive
        run: tar -zxf oss-cad-suite-linux-x64-20220502.tgz

      - name: Setup environment
        run: source ./oss-cad-suite/environment

      - name: run synthesis
        working-directory: ${{ matrix.project }}
        run: make local
